set_global_routing_layer_adjustment met9 0
set_global_routing_layer_adjustment met8 0
set_global_routing_layer_adjustment met7 0
set_global_routing_layer_adjustment met6 0
set_global_routing_layer_adjustment met5 0
set_global_routing_layer_adjustment met4 0
set_global_routing_layer_adjustment met3 0
set_global_routing_layer_adjustment met2 0
set_global_routing_layer_adjustment met1 0

set_routing_layers -signal $::env(MIN_ROUTING_LAYER)-$::env(MAX_ROUTING_LAYER)